include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: false
    use_key_in_widget_constructors: false
    avoid_catches_without_on_clauses: false
    use_setters_to_change_properties: false
    avoid_positional_boolean_parameters: false
    always_put_required_named_parameters_first: true
    avoid_empty_else: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_rethrow_when_possible: true
    constant_identifier_names: false
    use_build_context_synchronously: false
    unnecessary_string_escapes: false
    unnecessary_overrides: false
    implicit_call_tearoffs: false



analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "packages/**/*.*"
    #    - "test/**/*.*"
    - "**/*.yaml"
    - lib/app/runner.config.dart
    - lib/app/router/app_router.gr.dart
    - lib/generated/assets.gen.dart
    - lib/generated/fonts.gen.dart
    - lib/generated/locale_keys.gen.dart

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-arguments: 4
    maximum-nesting-level: 5
    source-lines-of-code: 80
  metrics-exclude:
    - test/**
  rules:
    # Common
    - avoid-accessing-collections-by-constant-index
    - avoid-accessing-other-classes-private-members
    - avoid-barrel-files
    - avoid-bottom-type-in-patterns
    - avoid-bottom-type-in-records
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-contradictory-expressions
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-duplicate-map-keys
    - avoid-duplicate-named-imports
    - avoid-duplicate-patterns
    - avoid-duplicate-switch-case-conditions
    - avoid-dynamic
    - avoid-excessive-expressions
    - avoid-extensions-on-records
    - avoid-inverted-boolean-checks
    - avoid-map-keys-contains
    - avoid-missing-enum-constant-in-map
    - avoid-missing-interpolation:
        ignore-non-string-types: true
    - avoid-misused-test-matchers
    - avoid-mutating-parameters
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-nested-futures
    - avoid-nested-records:
        acceptable-level: 2
    - avoid-nested-switch-expressions:
        acceptable-level: 1
    - avoid-nested-switches
    - avoid-not-encodable-in-to-json
    - avoid-one-field-records
    - avoid-redundant-else
    - avoid-self-assignment
    - avoid-self-compare
    - avoid-shadowed-extension-methods
    - avoid-throw-objects-without-tostring
    - avoid-unassigned-late-fields
    - avoid-unassigned-stream-subscriptions
    - avoid-unnecessary-call
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-futures
    - avoid-unnecessary-if
    - avoid-unnecessary-local-late
    - avoid-unnecessary-negations
    - avoid-unnecessary-nullable-return-type
    - avoid-unnecessary-reassignment
    - avoid-unnecessary-return
    - avoid-unnecessary-super
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-casts
    - avoid-unused-after-null-check
    - avoid-unused-generics
    - avoid-unused-parameters

    - binary-expression-operand-order
    - match-positional-field-names-on-assignment
    - member-ordering:
        - fields
        - getters-setters
        - constructors
        - methods
    - move-records-to-typedefs:
        min-fields: 5
        min-occurrences: 3
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-conditions
    - no-equal-nested-conditions
    - no-equal-switch-case
    - no-equal-switch-expression-cases
    - no-equal-then-else
    - no-object-declaration
    - prefer-bytes-builder
    - prefer-conditional-expressions
    - prefer-correct-for-loop-increment
    - prefer-correct-future-return-type
    - prefer-correct-json-casts
    - prefer-correct-stream-return-type
    - prefer-correct-test-file-name
    - prefer-declaring-const-constructor:
        allow-one: true
    - prefer-extracting-callbacks
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-parentheses-with-if-null
    - prefer-public-exception-classes
    - prefer-specific-cases-first
    - prefer-trailing-comma
    - prefer-unique-test-names
    - prefer-wildcard-pattern

    # Flutter
    - always-remove-listener
    - avoid-expanded-as-spacer
    - avoid-incomplete-copy-with
    - avoid-inherited-widget-in-initstate
    - avoid-late-context
    - avoid-missing-image-alt:
        allow-empty: true
    - avoid-returning-widgets:
        ignored-names:
          - testFunction
        ignored-annotations:
          - allowedAnnotation
    - avoid-shrink-wrap-in-lists
    - avoid-single-child-column-or-row
    - avoid-state-constructors
    - avoid-stateless-widget-initialized-fields
    - avoid-unnecessary-overrides-in-state
    - avoid-unnecessary-stateful-widgets
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - dispose-fields
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-dedicated-media-query-methods
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-sliver-prefix
    - prefer-text-rich
    - prefer-using-list-view
    - prefer-widget-private-members:
        ignore-static: true
    - proper-super-calls
    - use-setstate-synchronously

    # BLOC
    - avoid-passing-bloc-to-bloc
    - prefer-correct-bloc-provider
    - prefer-multi-bloc-provider

    # Equatable
    - list-all-equatable-fields

    # Get_IT
    - avoid-functions-in-register-singleton
