
targets:
  $default:
    sources:
      exclude: [ 'lib/core/services/db/database.dart' ]
    builders:
      json_serializable:
        options:
          explicit_to_json: true
  drift:
    dependencies: [ '$default' ]
    sources:
      - lib/core/services/db/database.dart
    builders:
      drift_dev:
        # These options change how drift generates code
        options:
          # Drift analyzes SQL queries at compile-time. For this purpose, it needs to know which sqlite3
          # features will be available. We depend on `sqlite3_flutter_libs`, which lets us use the latest
          # version with fts5 enabled.
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [ fts5 ]

          # This allows us to share a drift database across isolates (or different tabs on the web)
          generate_connect_constructor: true
          # These options are generally recommended: https://drift.simonbinder.eu/docs/advanced-features/builder_options/#recommended-options
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          scoped_dart_components: true
          write_from_json_string_constructor: true
          store_date_time_values_as_text: true


