name: spotify_playlist_helper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^8.0.0
  cached_network_image: ^3.3.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  envied: ^0.5.3
  easy_logger: ^0.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_inappwebview: ^6.0.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.8.1
  logger: ^2.2.0
  path: ^1.8.2
  path_provider: 2.1.2
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  injectable_generator: ^2.4.1
  isar_generator: ^3.1.0+1
  json_serializable: 6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launch_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true
