name: spotify_playlist_helper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.4.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  drift: ^2.8.0
  data_table_2: ^2.5.2
  dartz: ^0.10.1
  dio: ^5.2.1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_db_store: ^5.1.0
  envied: ^0.3.0+3
  easy_logger: ^0.0.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  flutter_inappwebview: ^6.0.0-beta.24
  freezed: ^2.3.4
  get_it: ^7.6.0
  injectable: ^2.1.1
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  path: ^1.8.2
  path_provider: 2.0.15
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  flutter_lints: ^2.0.0
  build_runner: '>=2.3.0 <4.0.0'
  dart_code_metrics: ^5.7.5
  drift_dev: ^2.8.2
  envied_generator: ^0.3.0+3
  injectable_generator: ^2.1.5
  json_serializable: 6.7.0



flutter:

  uses-material-design: true
