name: spotify_playlist_helper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.4
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  envied: ^0.5.2
  easy_logger: ^0.0.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.1.1
  flutter_inappwebview: ^6.0.0-beta.30
  freezed: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.2
  path_provider: 2.1.1
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  injectable_generator: ^2.4.1
  isar_generator: ^3.1.0+1
  json_serializable: 6.7.1



flutter:

  uses-material-design: true
